# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RABBYLAB
email: imjoeunha@gmail.com
description: Coding Experience
baseurl: "" # the subpath of your site, e.g. /blog
url: http://rabbylab.xyz/blog # the base hostname & protocol for your site
linkedin_username: joeunha
github_username:  joeunha

# Build settings
markdown: kramdown

# Gem list
gems: [jekyll-admin]
